// Typed models for the Github SDK (JSDoc typedefs).
//
// GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
// params (op.<name>.points[].args.params[]). Field/param types come from the
// canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
// @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
// edit by hand.

/**
 * @typedef {Object} Pull
 * @property {string} [active_lock_reason]
 * @property {number} additions
 * @property {Object} assignee
 * @property {Array} [assignees]
 * @property {string} author_association
 * @property {Object} auto_merge
 * @property {Object} base
 * @property {string} body
 * @property {number} changed_files
 * @property {string} closed_at
 * @property {number} comments
 * @property {string} comments_url
 * @property {string} [commit_message]
 * @property {string} [commit_title]
 * @property {number} commits
 * @property {string} commits_url
 * @property {string} created_at
 * @property {number} deletions
 * @property {string} diff_url
 * @property {boolean} [draft]
 * @property {Object} head
 * @property {string} [head_repo]
 * @property {string} html_url
 * @property {number} id
 * @property {number} [issue]
 * @property {string} issue_url
 * @property {Array} labels
 * @property {Object} links
 * @property {boolean} locked
 * @property {boolean} maintainer_can_modify
 * @property {string} merge_commit_sha
 * @property {string} [merge_method]
 * @property {boolean} mergeable
 * @property {string} mergeable_state
 * @property {boolean} merged
 * @property {string} merged_at
 * @property {Object} merged_by
 * @property {string} message
 * @property {Object} milestone
 * @property {string} node_id
 * @property {number} number
 * @property {string} patch_url
 * @property {boolean} [rebaseable]
 * @property {Array} [requested_reviewers]
 * @property {Array} [requested_teams]
 * @property {string} review_comment_url
 * @property {number} review_comments
 * @property {string} review_comments_url
 * @property {string} sha
 * @property {Object} stack
 * @property {string} state
 * @property {string} statuses_url
 * @property {string} title
 * @property {string} updated_at
 * @property {string} url
 * @property {Object} user
 */

/**
 * @typedef {Object} PullLoadMatch
 * @property {number} id
 * @property {string} owner
 * @property {string} repo
 */

/**
 * @typedef {Object} PullListMatch
 * @property {string} owner
 * @property {string} repo
 * @property {string} [base]
 * @property {string} [direction]
 * @property {string} [head]
 * @property {number} [page]
 * @property {number} [per_page]
 * @property {string} [sort]
 * @property {string} [state]
 */

/**
 * @typedef {Object} PullCreateData
 * @property {string} owner
 * @property {string} repo
 * @property {string} [active_lock_reason]
 * @property {number} additions
 * @property {Object} assignee
 * @property {Array} [assignees]
 * @property {string} author_association
 * @property {Object} auto_merge
 * @property {Object} base
 * @property {string} body
 * @property {number} changed_files
 * @property {string} closed_at
 * @property {number} comments
 * @property {string} comments_url
 * @property {string} [commit_message]
 * @property {string} [commit_title]
 * @property {number} commits
 * @property {string} commits_url
 * @property {string} created_at
 * @property {number} deletions
 * @property {string} diff_url
 * @property {boolean} [draft]
 * @property {Object} head
 * @property {string} [head_repo]
 * @property {string} html_url
 * @property {number} id
 * @property {number} [issue]
 * @property {string} issue_url
 * @property {Array} labels
 * @property {Object} links
 * @property {boolean} locked
 * @property {boolean} maintainer_can_modify
 * @property {string} merge_commit_sha
 * @property {string} [merge_method]
 * @property {boolean} mergeable
 * @property {string} mergeable_state
 * @property {boolean} merged
 * @property {string} merged_at
 * @property {Object} merged_by
 * @property {string} message
 * @property {Object} milestone
 * @property {string} node_id
 * @property {number} number
 * @property {string} patch_url
 * @property {boolean} [rebaseable]
 * @property {Array} [requested_reviewers]
 * @property {Array} [requested_teams]
 * @property {string} review_comment_url
 * @property {number} review_comments
 * @property {string} review_comments_url
 * @property {string} sha
 * @property {Object} stack
 * @property {string} state
 * @property {string} statuses_url
 * @property {string} title
 * @property {string} updated_at
 * @property {string} url
 * @property {Object} user
 */

/**
 * @typedef {Object} PullUpdateData
 * @property {number} id
 * @property {string} owner
 * @property {string} repo
 * @property {string} [active_lock_reason]
 * @property {number} [additions]
 * @property {Object} [assignee]
 * @property {Array} [assignees]
 * @property {string} [author_association]
 * @property {Object} [auto_merge]
 * @property {Object} [base]
 * @property {string} [body]
 * @property {number} [changed_files]
 * @property {string} [closed_at]
 * @property {number} [comments]
 * @property {string} [comments_url]
 * @property {string} [commit_message]
 * @property {string} [commit_title]
 * @property {number} [commits]
 * @property {string} [commits_url]
 * @property {string} [created_at]
 * @property {number} [deletions]
 * @property {string} [diff_url]
 * @property {boolean} [draft]
 * @property {Object} [head]
 * @property {string} [head_repo]
 * @property {string} [html_url]
 * @property {number} [issue]
 * @property {string} [issue_url]
 * @property {Array} [labels]
 * @property {Object} [links]
 * @property {boolean} [locked]
 * @property {boolean} [maintainer_can_modify]
 * @property {string} [merge_commit_sha]
 * @property {string} [merge_method]
 * @property {boolean} [mergeable]
 * @property {string} [mergeable_state]
 * @property {boolean} [merged]
 * @property {string} [merged_at]
 * @property {Object} [merged_by]
 * @property {string} [message]
 * @property {Object} [milestone]
 * @property {string} [node_id]
 * @property {number} [number]
 * @property {string} [patch_url]
 * @property {boolean} [rebaseable]
 * @property {Array} [requested_reviewers]
 * @property {Array} [requested_teams]
 * @property {string} [review_comment_url]
 * @property {number} [review_comments]
 * @property {string} [review_comments_url]
 * @property {string} [sha]
 * @property {Object} [stack]
 * @property {string} [state]
 * @property {string} [statuses_url]
 * @property {string} [title]
 * @property {string} [updated_at]
 * @property {string} [url]
 * @property {Object} [user]
 */

/**
 * @typedef {Object} Repo
 * @property {boolean} [allow_auto_merge]
 * @property {boolean} [allow_forking]
 * @property {boolean} [allow_merge_commit]
 * @property {boolean} [allow_rebase_merge]
 * @property {boolean} [allow_squash_merge]
 * @property {boolean} [allow_update_branch]
 * @property {boolean} [anonymous_access_enabled]
 * @property {string} archive_url
 * @property {boolean} archived
 * @property {string} assignees_url
 * @property {boolean} [auto_init]
 * @property {string} blobs_url
 * @property {string} branches_url
 * @property {string} clone_url
 * @property {Object} code_of_conduct
 * @property {Object} [code_search_index_status]
 * @property {string} collaborators_url
 * @property {string} comments_url
 * @property {string} commits_url
 * @property {string} compare_url
 * @property {string} contents_url
 * @property {string} contributors_url
 * @property {string} created_at
 * @property {Object} [custom_properties]
 * @property {string} default_branch
 * @property {boolean} [delete_branch_on_merge]
 * @property {string} deployments_url
 * @property {string} description
 * @property {boolean} disabled
 * @property {string} downloads_url
 * @property {string} events_url
 * @property {boolean} fork
 * @property {number} forks
 * @property {number} forks_count
 * @property {string} forks_url
 * @property {string} full_name
 * @property {string} git_commits_url
 * @property {string} git_refs_url
 * @property {string} git_tags_url
 * @property {string} git_url
 * @property {string} [gitignore_template]
 * @property {boolean} has_discussions
 * @property {boolean} [has_downloads]
 * @property {boolean} has_issues
 * @property {boolean} has_pages
 * @property {boolean} has_projects
 * @property {boolean} [has_pull_requests]
 * @property {boolean} has_wiki
 * @property {string} homepage
 * @property {string} hooks_url
 * @property {string} html_url
 * @property {number} id
 * @property {boolean} [is_template]
 * @property {string} issue_comment_url
 * @property {string} issue_events_url
 * @property {string} issues_url
 * @property {string} keys_url
 * @property {string} labels_url
 * @property {string} language
 * @property {string} languages_url
 * @property {Object} license
 * @property {string} [license_template]
 * @property {string} [master_branch]
 * @property {string} [merge_commit_message]
 * @property {string} [merge_commit_title]
 * @property {string} merges_url
 * @property {string} milestones_url
 * @property {string} mirror_url
 * @property {string} name
 * @property {number} network_count
 * @property {string} node_id
 * @property {string} notifications_url
 * @property {number} open_issues
 * @property {number} open_issues_count
 * @property {Object} organization
 * @property {Object} owner
 * @property {Object} parent
 * @property {Object} permissions
 * @property {boolean} private
 * @property {string} [pull_request_creation_policy]
 * @property {string} pulls_url
 * @property {string} pushed_at
 * @property {string} releases_url
 * @property {Object} [security_and_analysis]
 * @property {number} size
 * @property {Object} source
 * @property {string} [squash_merge_commit_message]
 * @property {string} [squash_merge_commit_title]
 * @property {string} ssh_url
 * @property {number} stargazers_count
 * @property {string} stargazers_url
 * @property {string} [starred_at]
 * @property {string} statuses_url
 * @property {number} subscribers_count
 * @property {string} subscribers_url
 * @property {string} subscription_url
 * @property {string} svn_url
 * @property {string} tags_url
 * @property {number} [team_id]
 * @property {string} teams_url
 * @property {string} [temp_clone_token]
 * @property {Object} template_repository
 * @property {Array} [topics]
 * @property {string} trees_url
 * @property {string} updated_at
 * @property {string} url
 * @property {boolean} [use_squash_pr_title_as_default]
 * @property {string} [visibility]
 * @property {number} watchers
 * @property {number} watchers_count
 * @property {boolean} [web_commit_signoff_required]
 */

/**
 * @typedef {Object} RepoLoadMatch
 * @property {string} owner
 * @property {string} repo
 */

/**
 * @typedef {Object} RepoListMatch
 * @property {string} [affiliation]
 * @property {string} [before]
 * @property {string} [direction]
 * @property {number} [page]
 * @property {number} [per_page]
 * @property {string} [since]
 * @property {string} [sort]
 * @property {string} [type]
 * @property {string} [visibility]
 */

/**
 * @typedef {Object} RepoCreateData
 * @property {boolean} [allow_auto_merge]
 * @property {boolean} [allow_forking]
 * @property {boolean} [allow_merge_commit]
 * @property {boolean} [allow_rebase_merge]
 * @property {boolean} [allow_squash_merge]
 * @property {boolean} [allow_update_branch]
 * @property {boolean} [anonymous_access_enabled]
 * @property {string} archive_url
 * @property {boolean} archived
 * @property {string} assignees_url
 * @property {boolean} [auto_init]
 * @property {string} blobs_url
 * @property {string} branches_url
 * @property {string} clone_url
 * @property {Object} code_of_conduct
 * @property {Object} [code_search_index_status]
 * @property {string} collaborators_url
 * @property {string} comments_url
 * @property {string} commits_url
 * @property {string} compare_url
 * @property {string} contents_url
 * @property {string} contributors_url
 * @property {string} created_at
 * @property {Object} [custom_properties]
 * @property {string} default_branch
 * @property {boolean} [delete_branch_on_merge]
 * @property {string} deployments_url
 * @property {string} description
 * @property {boolean} disabled
 * @property {string} downloads_url
 * @property {string} events_url
 * @property {boolean} fork
 * @property {number} forks
 * @property {number} forks_count
 * @property {string} forks_url
 * @property {string} full_name
 * @property {string} git_commits_url
 * @property {string} git_refs_url
 * @property {string} git_tags_url
 * @property {string} git_url
 * @property {string} [gitignore_template]
 * @property {boolean} has_discussions
 * @property {boolean} [has_downloads]
 * @property {boolean} has_issues
 * @property {boolean} has_pages
 * @property {boolean} has_projects
 * @property {boolean} [has_pull_requests]
 * @property {boolean} has_wiki
 * @property {string} homepage
 * @property {string} hooks_url
 * @property {string} html_url
 * @property {number} id
 * @property {boolean} [is_template]
 * @property {string} issue_comment_url
 * @property {string} issue_events_url
 * @property {string} issues_url
 * @property {string} keys_url
 * @property {string} labels_url
 * @property {string} language
 * @property {string} languages_url
 * @property {Object} license
 * @property {string} [license_template]
 * @property {string} [master_branch]
 * @property {string} [merge_commit_message]
 * @property {string} [merge_commit_title]
 * @property {string} merges_url
 * @property {string} milestones_url
 * @property {string} mirror_url
 * @property {string} name
 * @property {number} network_count
 * @property {string} node_id
 * @property {string} notifications_url
 * @property {number} open_issues
 * @property {number} open_issues_count
 * @property {Object} organization
 * @property {Object} owner
 * @property {Object} parent
 * @property {Object} permissions
 * @property {boolean} private
 * @property {string} [pull_request_creation_policy]
 * @property {string} pulls_url
 * @property {string} pushed_at
 * @property {string} releases_url
 * @property {Object} [security_and_analysis]
 * @property {number} size
 * @property {Object} source
 * @property {string} [squash_merge_commit_message]
 * @property {string} [squash_merge_commit_title]
 * @property {string} ssh_url
 * @property {number} stargazers_count
 * @property {string} stargazers_url
 * @property {string} [starred_at]
 * @property {string} statuses_url
 * @property {number} subscribers_count
 * @property {string} subscribers_url
 * @property {string} subscription_url
 * @property {string} svn_url
 * @property {string} tags_url
 * @property {number} [team_id]
 * @property {string} teams_url
 * @property {string} [temp_clone_token]
 * @property {Object} template_repository
 * @property {Array} [topics]
 * @property {string} trees_url
 * @property {string} updated_at
 * @property {string} url
 * @property {boolean} [use_squash_pr_title_as_default]
 * @property {string} [visibility]
 * @property {number} watchers
 * @property {number} watchers_count
 * @property {boolean} [web_commit_signoff_required]
 */

/**
 * @typedef {Object} RepoUpdateData
 * @property {string} owner
 * @property {string} repo
 * @property {boolean} [allow_auto_merge]
 * @property {boolean} [allow_forking]
 * @property {boolean} [allow_merge_commit]
 * @property {boolean} [allow_rebase_merge]
 * @property {boolean} [allow_squash_merge]
 * @property {boolean} [allow_update_branch]
 * @property {boolean} [anonymous_access_enabled]
 * @property {string} [archive_url]
 * @property {boolean} [archived]
 * @property {string} [assignees_url]
 * @property {boolean} [auto_init]
 * @property {string} [blobs_url]
 * @property {string} [branches_url]
 * @property {string} [clone_url]
 * @property {Object} [code_of_conduct]
 * @property {Object} [code_search_index_status]
 * @property {string} [collaborators_url]
 * @property {string} [comments_url]
 * @property {string} [commits_url]
 * @property {string} [compare_url]
 * @property {string} [contents_url]
 * @property {string} [contributors_url]
 * @property {string} [created_at]
 * @property {Object} [custom_properties]
 * @property {string} [default_branch]
 * @property {boolean} [delete_branch_on_merge]
 * @property {string} [deployments_url]
 * @property {string} [description]
 * @property {boolean} [disabled]
 * @property {string} [downloads_url]
 * @property {string} [events_url]
 * @property {boolean} [fork]
 * @property {number} [forks]
 * @property {number} [forks_count]
 * @property {string} [forks_url]
 * @property {string} [full_name]
 * @property {string} [git_commits_url]
 * @property {string} [git_refs_url]
 * @property {string} [git_tags_url]
 * @property {string} [git_url]
 * @property {string} [gitignore_template]
 * @property {boolean} [has_discussions]
 * @property {boolean} [has_downloads]
 * @property {boolean} [has_issues]
 * @property {boolean} [has_pages]
 * @property {boolean} [has_projects]
 * @property {boolean} [has_pull_requests]
 * @property {boolean} [has_wiki]
 * @property {string} [homepage]
 * @property {string} [hooks_url]
 * @property {string} [html_url]
 * @property {number} [id]
 * @property {boolean} [is_template]
 * @property {string} [issue_comment_url]
 * @property {string} [issue_events_url]
 * @property {string} [issues_url]
 * @property {string} [keys_url]
 * @property {string} [labels_url]
 * @property {string} [language]
 * @property {string} [languages_url]
 * @property {Object} [license]
 * @property {string} [license_template]
 * @property {string} [master_branch]
 * @property {string} [merge_commit_message]
 * @property {string} [merge_commit_title]
 * @property {string} [merges_url]
 * @property {string} [milestones_url]
 * @property {string} [mirror_url]
 * @property {string} [name]
 * @property {number} [network_count]
 * @property {string} [node_id]
 * @property {string} [notifications_url]
 * @property {number} [open_issues]
 * @property {number} [open_issues_count]
 * @property {Object} [organization]
 * @property {Object} [parent]
 * @property {Object} [permissions]
 * @property {boolean} [private]
 * @property {string} [pull_request_creation_policy]
 * @property {string} [pulls_url]
 * @property {string} [pushed_at]
 * @property {string} [releases_url]
 * @property {Object} [security_and_analysis]
 * @property {number} [size]
 * @property {Object} [source]
 * @property {string} [squash_merge_commit_message]
 * @property {string} [squash_merge_commit_title]
 * @property {string} [ssh_url]
 * @property {number} [stargazers_count]
 * @property {string} [stargazers_url]
 * @property {string} [starred_at]
 * @property {string} [statuses_url]
 * @property {number} [subscribers_count]
 * @property {string} [subscribers_url]
 * @property {string} [subscription_url]
 * @property {string} [svn_url]
 * @property {string} [tags_url]
 * @property {number} [team_id]
 * @property {string} [teams_url]
 * @property {string} [temp_clone_token]
 * @property {Object} [template_repository]
 * @property {Array} [topics]
 * @property {string} [trees_url]
 * @property {string} [updated_at]
 * @property {string} [url]
 * @property {boolean} [use_squash_pr_title_as_default]
 * @property {string} [visibility]
 * @property {number} [watchers]
 * @property {number} [watchers_count]
 * @property {boolean} [web_commit_signoff_required]
 */

/**
 * @typedef {Object} RepoRemoveMatch
 * @property {string} owner
 * @property {string} repo
 */

