<?php
declare(strict_types=1);

// Github SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

GithubUtility::setRegistrar(function (GithubUtility $u): void {
    $u->clean = [GithubClean::class, 'call'];
    $u->done = [GithubDone::class, 'call'];
    $u->make_error = [GithubMakeError::class, 'call'];
    $u->feature_add = [GithubFeatureAdd::class, 'call'];
    $u->feature_hook = [GithubFeatureHook::class, 'call'];
    $u->feature_init = [GithubFeatureInit::class, 'call'];
    $u->fetcher = [GithubFetcher::class, 'call'];
    $u->make_fetch_def = [GithubMakeFetchDef::class, 'call'];
    $u->make_context = [GithubMakeContext::class, 'call'];
    $u->make_options = [GithubMakeOptions::class, 'call'];
    $u->make_request = [GithubMakeRequest::class, 'call'];
    $u->make_response = [GithubMakeResponse::class, 'call'];
    $u->make_result = [GithubMakeResult::class, 'call'];
    $u->make_point = [GithubMakePoint::class, 'call'];
    $u->make_spec = [GithubMakeSpec::class, 'call'];
    $u->make_url = [GithubMakeUrl::class, 'call'];
    $u->param = [GithubParam::class, 'call'];
    $u->prepare_auth = [GithubPrepareAuth::class, 'call'];
    $u->prepare_body = [GithubPrepareBody::class, 'call'];
    $u->prepare_headers = [GithubPrepareHeaders::class, 'call'];
    $u->prepare_method = [GithubPrepareMethod::class, 'call'];
    $u->prepare_params = [GithubPrepareParams::class, 'call'];
    $u->prepare_path = [GithubPreparePath::class, 'call'];
    $u->prepare_query = [GithubPrepareQuery::class, 'call'];
    $u->graphql_body = [GithubGraphql::class, 'body'];
    $u->graphql_errors = [GithubGraphql::class, 'errors'];
    $u->result_basic = [GithubResultBasic::class, 'call'];
    $u->result_body = [GithubResultBody::class, 'call'];
    $u->result_headers = [GithubResultHeaders::class, 'call'];
    $u->transform_request = [GithubTransformRequest::class, 'call'];
    $u->transform_response = [GithubTransformResponse::class, 'call'];
});
