# Typed models for the Github SDK.
#
# GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
# params (op.<name>.points[].args.params[]). Field/param types come from the
# canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
# @voxgig/apidef VALID_CANON). Do not edit by hand.
#
# These are TypedDicts, not dataclasses: the SDK ops return/accept plain dicts
# at runtime, and a TypedDict IS a dict shape, so the types match the runtime.
# Optional (req:false) keys are modelled as TypedDict key-optionality
# (total=False), split into a required base + total=False subclass when a type
# has both required and optional keys.

from __future__ import annotations

from typing import TypedDict, Any


class PullRequired(TypedDict):
    additions: int
    assignee: dict
    author_association: str
    auto_merge: dict
    base: dict
    body: str
    changed_files: int
    closed_at: str
    comments: int
    comments_url: str
    commits: int
    commits_url: str
    created_at: str
    deletions: int
    diff_url: str
    head: dict
    html_url: str
    id: int
    issue_url: str
    labels: list
    links: dict
    locked: bool
    maintainer_can_modify: bool
    merge_commit_sha: str
    mergeable: bool
    mergeable_state: str
    merged: bool
    merged_at: str
    merged_by: dict
    message: str
    milestone: dict
    node_id: str
    number: int
    patch_url: str
    review_comment_url: str
    review_comments: int
    review_comments_url: str
    sha: str
    stack: dict
    state: str
    statuses_url: str
    title: str
    updated_at: str
    url: str
    user: dict


class Pull(PullRequired, total=False):
    active_lock_reason: str
    assignees: list
    commit_message: str
    commit_title: str
    draft: bool
    head_repo: str
    issue: int
    merge_method: str
    rebaseable: bool
    requested_reviewers: list
    requested_teams: list


class PullLoadMatch(TypedDict):
    owner: str
    pull_number: int
    repo: str


class PullListMatch(TypedDict):
    owner: str
    repo: str


class PullCreateDataRequired(TypedDict):
    owner: str
    repo: str
    additions: int
    assignee: dict
    author_association: str
    auto_merge: dict
    base: dict
    body: str
    changed_files: int
    closed_at: str
    comments: int
    comments_url: str
    commits: int
    commits_url: str
    created_at: str
    deletions: int
    diff_url: str
    head: dict
    html_url: str
    id: int
    issue_url: str
    labels: list
    links: dict
    locked: bool
    maintainer_can_modify: bool
    merge_commit_sha: str
    mergeable: bool
    mergeable_state: str
    merged: bool
    merged_at: str
    merged_by: dict
    message: str
    milestone: dict
    node_id: str
    number: int
    patch_url: str
    review_comment_url: str
    review_comments: int
    review_comments_url: str
    sha: str
    stack: dict
    state: str
    statuses_url: str
    title: str
    updated_at: str
    url: str
    user: dict


class PullCreateData(PullCreateDataRequired, total=False):
    active_lock_reason: str
    assignees: list
    commit_message: str
    commit_title: str
    draft: bool
    head_repo: str
    issue: int
    merge_method: str
    rebaseable: bool
    requested_reviewers: list
    requested_teams: list


class PullUpdateDataRequired(TypedDict):
    owner: str
    pull_number: int
    repo: str


class PullUpdateData(PullUpdateDataRequired, total=False):
    active_lock_reason: str
    additions: int
    assignee: dict
    assignees: list
    author_association: str
    auto_merge: dict
    base: dict
    body: str
    changed_files: int
    closed_at: str
    comments: int
    comments_url: str
    commit_message: str
    commit_title: str
    commits: int
    commits_url: str
    created_at: str
    deletions: int
    diff_url: str
    draft: bool
    head: dict
    head_repo: str
    html_url: str
    id: int
    issue: int
    issue_url: str
    labels: list
    links: dict
    locked: bool
    maintainer_can_modify: bool
    merge_commit_sha: str
    merge_method: str
    mergeable: bool
    mergeable_state: str
    merged: bool
    merged_at: str
    merged_by: dict
    message: str
    milestone: dict
    node_id: str
    number: int
    patch_url: str
    rebaseable: bool
    requested_reviewers: list
    requested_teams: list
    review_comment_url: str
    review_comments: int
    review_comments_url: str
    sha: str
    stack: dict
    state: str
    statuses_url: str
    title: str
    updated_at: str
    url: str
    user: dict


class RepoRequired(TypedDict):
    archive_url: str
    archived: bool
    assignees_url: str
    blobs_url: str
    branches_url: str
    clone_url: str
    code_of_conduct: dict
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    created_at: str
    default_branch: str
    deployments_url: str
    description: str
    disabled: bool
    downloads_url: str
    events_url: str
    fork: bool
    forks: int
    forks_count: int
    forks_url: str
    full_name: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    has_discussions: bool
    has_issues: bool
    has_pages: bool
    has_projects: bool
    has_wiki: bool
    homepage: str
    hooks_url: str
    html_url: str
    id: int
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    language: str
    languages_url: str
    license: dict
    merges_url: str
    milestones_url: str
    mirror_url: str
    name: str
    network_count: int
    node_id: str
    notifications_url: str
    open_issues: int
    open_issues_count: int
    organization: dict
    owner: dict
    parent: dict
    permissions: dict
    private: bool
    pulls_url: str
    pushed_at: str
    releases_url: str
    size: int
    source: dict
    ssh_url: str
    stargazers_count: int
    stargazers_url: str
    statuses_url: str
    subscribers_count: int
    subscribers_url: str
    subscription_url: str
    svn_url: str
    tags_url: str
    teams_url: str
    template_repository: dict
    trees_url: str
    updated_at: str
    url: str
    watchers: int
    watchers_count: int


class Repo(RepoRequired, total=False):
    allow_auto_merge: bool
    allow_forking: bool
    allow_merge_commit: bool
    allow_rebase_merge: bool
    allow_squash_merge: bool
    allow_update_branch: bool
    anonymous_access_enabled: bool
    auto_init: bool
    code_search_index_status: dict
    custom_properties: dict
    delete_branch_on_merge: bool
    gitignore_template: str
    has_downloads: bool
    has_pull_requests: bool
    is_template: bool
    license_template: str
    master_branch: str
    merge_commit_message: str
    merge_commit_title: str
    pull_request_creation_policy: str
    security_and_analysis: dict
    squash_merge_commit_message: str
    squash_merge_commit_title: str
    starred_at: str
    team_id: int
    temp_clone_token: str
    topics: list
    use_squash_pr_title_as_default: bool
    visibility: str
    web_commit_signoff_required: bool


class RepoLoadMatch(TypedDict):
    owner: str
    repo: str


class RepoListMatch(TypedDict, total=False):
    allow_auto_merge: bool
    allow_forking: bool
    allow_merge_commit: bool
    allow_rebase_merge: bool
    allow_squash_merge: bool
    allow_update_branch: bool
    anonymous_access_enabled: bool
    archive_url: str
    archived: bool
    assignees_url: str
    auto_init: bool
    blobs_url: str
    branches_url: str
    clone_url: str
    code_of_conduct: dict
    code_search_index_status: dict
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    created_at: str
    custom_properties: dict
    default_branch: str
    delete_branch_on_merge: bool
    deployments_url: str
    description: str
    disabled: bool
    downloads_url: str
    events_url: str
    fork: bool
    forks: int
    forks_count: int
    forks_url: str
    full_name: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    gitignore_template: str
    has_discussions: bool
    has_downloads: bool
    has_issues: bool
    has_pages: bool
    has_projects: bool
    has_pull_requests: bool
    has_wiki: bool
    homepage: str
    hooks_url: str
    html_url: str
    id: int
    is_template: bool
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    language: str
    languages_url: str
    license: dict
    license_template: str
    master_branch: str
    merge_commit_message: str
    merge_commit_title: str
    merges_url: str
    milestones_url: str
    mirror_url: str
    name: str
    network_count: int
    node_id: str
    notifications_url: str
    open_issues: int
    open_issues_count: int
    organization: dict
    owner: dict
    parent: dict
    permissions: dict
    private: bool
    pull_request_creation_policy: str
    pulls_url: str
    pushed_at: str
    releases_url: str
    security_and_analysis: dict
    size: int
    source: dict
    squash_merge_commit_message: str
    squash_merge_commit_title: str
    ssh_url: str
    stargazers_count: int
    stargazers_url: str
    starred_at: str
    statuses_url: str
    subscribers_count: int
    subscribers_url: str
    subscription_url: str
    svn_url: str
    tags_url: str
    team_id: int
    teams_url: str
    temp_clone_token: str
    template_repository: dict
    topics: list
    trees_url: str
    updated_at: str
    url: str
    use_squash_pr_title_as_default: bool
    visibility: str
    watchers: int
    watchers_count: int
    web_commit_signoff_required: bool


class RepoCreateDataRequired(TypedDict):
    archive_url: str
    archived: bool
    assignees_url: str
    blobs_url: str
    branches_url: str
    clone_url: str
    code_of_conduct: dict
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    created_at: str
    default_branch: str
    deployments_url: str
    description: str
    disabled: bool
    downloads_url: str
    events_url: str
    fork: bool
    forks: int
    forks_count: int
    forks_url: str
    full_name: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    has_discussions: bool
    has_issues: bool
    has_pages: bool
    has_projects: bool
    has_wiki: bool
    homepage: str
    hooks_url: str
    html_url: str
    id: int
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    language: str
    languages_url: str
    license: dict
    merges_url: str
    milestones_url: str
    mirror_url: str
    name: str
    network_count: int
    node_id: str
    notifications_url: str
    open_issues: int
    open_issues_count: int
    organization: dict
    owner: dict
    parent: dict
    permissions: dict
    private: bool
    pulls_url: str
    pushed_at: str
    releases_url: str
    size: int
    source: dict
    ssh_url: str
    stargazers_count: int
    stargazers_url: str
    statuses_url: str
    subscribers_count: int
    subscribers_url: str
    subscription_url: str
    svn_url: str
    tags_url: str
    teams_url: str
    template_repository: dict
    trees_url: str
    updated_at: str
    url: str
    watchers: int
    watchers_count: int


class RepoCreateData(RepoCreateDataRequired, total=False):
    allow_auto_merge: bool
    allow_forking: bool
    allow_merge_commit: bool
    allow_rebase_merge: bool
    allow_squash_merge: bool
    allow_update_branch: bool
    anonymous_access_enabled: bool
    auto_init: bool
    code_search_index_status: dict
    custom_properties: dict
    delete_branch_on_merge: bool
    gitignore_template: str
    has_downloads: bool
    has_pull_requests: bool
    is_template: bool
    license_template: str
    master_branch: str
    merge_commit_message: str
    merge_commit_title: str
    pull_request_creation_policy: str
    security_and_analysis: dict
    squash_merge_commit_message: str
    squash_merge_commit_title: str
    starred_at: str
    team_id: int
    temp_clone_token: str
    topics: list
    use_squash_pr_title_as_default: bool
    visibility: str
    web_commit_signoff_required: bool


class RepoUpdateDataRequired(TypedDict):
    owner: str
    repo: str


class RepoUpdateData(RepoUpdateDataRequired, total=False):
    allow_auto_merge: bool
    allow_forking: bool
    allow_merge_commit: bool
    allow_rebase_merge: bool
    allow_squash_merge: bool
    allow_update_branch: bool
    anonymous_access_enabled: bool
    archive_url: str
    archived: bool
    assignees_url: str
    auto_init: bool
    blobs_url: str
    branches_url: str
    clone_url: str
    code_of_conduct: dict
    code_search_index_status: dict
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    created_at: str
    custom_properties: dict
    default_branch: str
    delete_branch_on_merge: bool
    deployments_url: str
    description: str
    disabled: bool
    downloads_url: str
    events_url: str
    fork: bool
    forks: int
    forks_count: int
    forks_url: str
    full_name: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    gitignore_template: str
    has_discussions: bool
    has_downloads: bool
    has_issues: bool
    has_pages: bool
    has_projects: bool
    has_pull_requests: bool
    has_wiki: bool
    homepage: str
    hooks_url: str
    html_url: str
    id: int
    is_template: bool
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    language: str
    languages_url: str
    license: dict
    license_template: str
    master_branch: str
    merge_commit_message: str
    merge_commit_title: str
    merges_url: str
    milestones_url: str
    mirror_url: str
    name: str
    network_count: int
    node_id: str
    notifications_url: str
    open_issues: int
    open_issues_count: int
    organization: dict
    parent: dict
    permissions: dict
    private: bool
    pull_request_creation_policy: str
    pulls_url: str
    pushed_at: str
    releases_url: str
    security_and_analysis: dict
    size: int
    source: dict
    squash_merge_commit_message: str
    squash_merge_commit_title: str
    ssh_url: str
    stargazers_count: int
    stargazers_url: str
    starred_at: str
    statuses_url: str
    subscribers_count: int
    subscribers_url: str
    subscription_url: str
    svn_url: str
    tags_url: str
    team_id: int
    teams_url: str
    temp_clone_token: str
    template_repository: dict
    topics: list
    trees_url: str
    updated_at: str
    url: str
    use_squash_pr_title_as_default: bool
    visibility: str
    watchers: int
    watchers_count: int
    web_commit_signoff_required: bool


class RepoRemoveMatch(TypedDict):
    owner: str
    repo: str
